# Generated by Django 4.2.5 on 2023-09-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(default='hi', upload_to=''),
            preserve_default=False,
        ),
    ]
